"""empty message

Revision ID: 043f676445f0
Revises: 818117a71588
Create Date: 2026-05-13 22:27:16.615888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '043f676445f0'
down_revision: Union[str, Sequence[str], None] = '818117a71588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('debit_account_id', sa.Integer(), nullable=True),
    sa.Column('credit_account_id', sa.Integer(), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.drop_index(op.f('ix_jounral_entries_id'), table_name='jounral_entries')
    op.drop_table('jounral_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jounral_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('credit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['chart_of_accounts.id'], name=op.f('jounral_entries_credit_account_id_fkey')),
    sa.ForeignKeyConstraint(['debit_account_id'], ['chart_of_accounts.id'], name=op.f('jounral_entries_debit_account_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('jounral_entries_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jounral_entries_pkey'))
    )
    op.create_index(op.f('ix_jounral_entries_id'), 'jounral_entries', ['id'], unique=False)
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
